name: .NET test

on: push

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Modify code for testing
      run: sed -i 's/AddSingleton/AddScoped/g' ./backend/Program.cs
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./backend_tests
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./backend_tests
    - name: Test
      run: |
        dotnet test --no-build --verbosity normal --collect:"Code Coverage"
        mv -v ./TestResults/*/*.* ./TestResults/
        for i in ./TestResults/*.coverage ; do mv "$i" "./TestResults/1.coverage" ; done
      working-directory: ./backend_tests
    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v2
      with:
        files: ./backend_tests/TestResults/1.coverage
