name: .NET test

on: push

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./backend_tests
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./backend_tests
    - name: Test
      run: dotnet test --no-build --verbosity normal --collect:"Code Coverage"
      working-directory: ./backend_tests
    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v2
      with:
        files: ./backend_tests/TestResults/**/*.coverage
