name: flutter_test
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2.2.1
        with:
          flutter-version: '2.10.0'
      - name: Restore packages
        working-directory: ./frontend
        run: flutter pub get
      - name: Analyze
        run: flutter analyze
        working-directory: ./frontend
      - name: Run tests
        run: flutter test --coverage
        working-directory: ./frontend
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1.0.2
        with:
          working-directory: ./frontend
